/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: BuyMeADrink.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @BuyMeADrink: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@BuyMeADrink()
	{
		this.StartPassage = "Introduction";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Introduction

	void passage1_Init()
	{
		this.Passages[@"Introduction"] = new StoryPassage(@"Introduction", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hello!");
		yield return lineBreak();
		yield return link("Hi, How are you!", "Second", null);
		yield break;
	}


	// .............
	// #2: Second

	void passage2_Init()
	{
		this.Passages[@"Second"] = new StoryPassage(@"Second", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("I'm doing well, but I'm a bit thristy.");
		yield return lineBreak();
		yield return link("Then what can I get you?", "Order Up", null);
		yield break;
	}


	// .............
	// #3: Order Up

	void passage3_Init()
	{
		this.Passages[@"Order Up"] = new StoryPassage(@"Order Up", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("I would like a \"DRINK\"!");
		yield break;
	}


}