/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Testerz.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Testerz: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Testerz()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hello, How are you! ");
		yield return lineBreak();
		yield return link("Good ", "They Good", null);
		yield return lineBreak();
		yield return link("Bad ", "They Bad", null);
		yield break;
	}


	// .............
	// #2:  They Good

	void passage2_Init()
	{
		this.Passages[@"They Good"] = new StoryPassage(@"They Good", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("That's good! ");
		yield return lineBreak();
		yield return link("(Move On) ", "Good End", null);
		yield break;
	}


	// .............
	// #3:  They Bad

	void passage3_Init()
	{
		this.Passages[@"They Bad"] = new StoryPassage(@"They Bad", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("I'm sorry you feel that way. I hope you feel better soon!");
		yield return lineBreak();
		yield return link("Thank You! ", "Good End", null);
		yield break;
	}


	// .............
	// #4:  Good End

	void passage4_Init()
	{
		this.Passages[@"Good End"] = new StoryPassage(@"Good End", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Good-Bye and have a wonderful day!");
		yield return lineBreak();
		yield return link("(Leave) ", "Ending", null);
		yield break;
	}


	// .............
	// #5:  Ending

	void passage5_Init()
	{
		this.Passages[@"Ending"] = new StoryPassage(@"Ending", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("THE END");
		yield break;
	}


}