/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Day1Pt1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Day1Pt1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Day1Pt1()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("A barbarian and an orc walk into a bar...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("continue", "continue", null);
		yield break;
	}


	// .............
	// #2: continue

	void passage2_Init()
	{
		this.Passages[@"continue"] = new StoryPassage(@"continue", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Stefan the Barbarian: And there I was, traveling up the mountainside, when a giant beast arose from the ground. It was as tall as a mountain, it was-");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Gustav: You disturbed the rest of a stone giant you imbecile.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Stefan: Sir, you deeply offend me. I bravely fought a stone giant.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Gustave: Stone giants are peaceful unless you go clunking around on top of them.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Could you guys maybe keep it down?", "Exit Gustav", null);
		yield return lineBreak();
		yield return link("The Stone Giants are somewhat peaceful.", "Exit Gustav", null);
		yield return lineBreak();
		yield return link("It’s just a story, Gustav.", "Exit Gustav", null);
		yield return lineBreak();
		yield return link("Watch", "Exit Gustav", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Exit Gustav

	void passage3_Init()
	{
		this.Passages[@"Exit Gustav"] = new StoryPassage(@"Exit Gustav", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Stefan: I even took home some nifty ancient tablet. I'm sure it's worth a fortune.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Gustav sighs, clearly having had enough of this.");
		yield break;
	}


}