/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Day2Pt2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Day2Pt2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Day2Pt2()
	{
		this.StartPassage = "Untitled Passage";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Untitled Passage

	void passage1_Init()
	{
		this.Passages[@"Untitled Passage"] = new StoryPassage(@"Untitled Passage", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Stefan: Barkeep! A round on me! Immediately.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Steve, calm down.", "Steve, calm down.", null);
		yield break;
	}


	// .............
	// #2: Steve, calm down.

	void passage2_Init()
	{
		this.Passages[@"Steve, calm down."] = new StoryPassage(@"Steve, calm down.", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Stefan: Right, right, where are my manners.  Sorry about yesterday. You know how it is. Gustav is just always on my case. I’m an adventurer! I can't be held back by NICETIES.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("He's probably just upset that you're kind of a murderer.", "He's probably just upset that you're kind of a murderer.", null);
		yield return lineBreak();
		yield return link("This is a dangerous world full of dangerous creatures. Makes sense to be a bit agressive.", "This is a dangerous world full of dangerous creatures. Makes sense to be a bit agressive.", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: He's probably just upset that you're kind of a murderer.

	void passage3_Init()
	{
		this.Passages[@"He's probably just upset that you're kind of a murderer."] = new StoryPassage(@"He's probably just upset that you're kind of a murderer.", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Stefan: It's mostly monsters! It's just sometimes they get in the way. Of my sword.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("cont.", "cont.", null);
		yield break;
	}


	// .............
	// #4: This is a dangerous world full of dangerous creatures. Makes sense to be a bit agressive.

	void passage4_Init()
	{
		this.Passages[@"This is a dangerous world full of dangerous creatures. Makes sense to be a bit agressive."] = new StoryPassage(@"This is a dangerous world full of dangerous creatures. Makes sense to be a bit agressive.", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Exactly! I go places, dangerous places, and perform amazing feats of heroism!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("cont.", "cont.", null);
		yield break;
	}


	// .............
	// #5: cont.

	void passage5_Init()
	{
		this.Passages[@"cont."] = new StoryPassage(@"cont.", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Stefan: But mostly it’s fine. For instance, one time, I came upon this town, and I helped them rid the lands of this huge goblin infestation. I threw my spear from, I swear, a hundred yards, and nailed the Goblin King straight through the head.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You cleared out the ENTIRE infestation?", "Drinks", null);
		yield return lineBreak();
		yield return link("You're the kind of man I wish I could be, Stefan", "Drinks", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Drinks

	void passage6_Init()
	{
		this.Passages[@"Drinks"] = new StoryPassage(@"Drinks", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Stefan: Indeed, I had to kill hundreds of goblins. An entire village was found. But enough chit chat! Give me your most heroic drink!");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


}