/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Day2Pt1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Day2Pt1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Day2Pt1()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Gustav: Good Morning!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You’re here quite early. We don’t open for a few more minutes.", "Continue", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Continue

	void passage2_Init()
	{
		this.Passages[@"Continue"] = new StoryPassage(@"Continue", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Gustav: Quite all right. I just needed the break before I returned to my studies.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Where do you study?", "Apothecary", null);
		yield return lineBreak();
		yield return link("What was that with Stefan last night?", "Stefan", null);
		yield break;
	}


	// .............
	// #3: Apothecary

	void passage3_Init()
	{
		this.Passages[@"Apothecary"] = new StoryPassage(@"Apothecary", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("I am a scholar serving under the local princeps. I’ve kept their libraries and research for the last few years. It’s quite rewarding.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Really, I studied at an apothecary once myself.", "ApothecaryII", null);
		yield return lineBreak();
		yield return link("What was that with Stefan last night?", "StefanII", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: Stefan

	void passage4_Init()
	{
		this.Passages[@"Stefan"] = new StoryPassage(@"Stefan", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Gustav: Stefan is a reckless fiend who runs around countrysides killing everything in his wake. It would be good news for us all if one of these days his recklessness earned him what he deserves. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("That's dispicable", "End", null);
		yield return lineBreak();
		yield return link("I'll think about it.", "End", null);
		yield return lineBreak();
		yield return link("I know you're upset, but maybe a drink to calm you down instead?", "End", null);
		yield break;
	}


	// .............
	// #5: ApothecaryII

	void passage5_Init()
	{
		this.Passages[@"ApothecaryII"] = new StoryPassage(@"ApothecaryII", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Gustav: Oh really? That’s quite fascinating. When I was a boy I had wanted to study alchemy myself. Not very easy to find schools these days, however.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I still have some old ingredients around here somewhere.", "ApothecaryIII", null);
		yield return lineBreak();
		yield return link("What was that with Stefan last night?", "StefanII", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: StefanII

	void passage6_Init()
	{
		this.Passages[@"StefanII"] = new StoryPassage(@"StefanII", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Gustav: Stefan is a reckless fiend who runs around countrysides killing everything in his wake. It would be good news for us all if one of these days his recklessness earned him what he deserves. You could do it. Surely you must know poisons if you studied as you said you did.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("That's dispicable", "End", null);
		yield return lineBreak();
		yield return link("I'll think about it.", "End", null);
		yield return lineBreak();
		yield return link("I know you're upset, but maybe a drink to calm you down instead?", "End", null);
		yield break;
	}


	// .............
	// #7: ApothecaryIII

	void passage7_Init()
	{
		this.Passages[@"ApothecaryIII"] = new StoryPassage(@"ApothecaryIII", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Gustav: You must show me sometime. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What was that with Stefan last night?", "StefanII", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: End

	void passage8_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Gustav: Well if it's all the same to you I should go, but you should at least think about it. ");
		yield break;
	}


}